# mkosi.conf
[Distribution]
Distribution=fedora
Release=44
RepositoryKeyFetch=yes

[Build]
CacheDirectory=mkosi.cache
Environment=CXX26_FLAGS="-std=gnu++26 -O3"
WithNetwork=yes

[Output]
Format=directory
OutputDirectory=mkosi.output/

[Content]
BuildPackages=
  git
Packages=
  busybox
  openssh-server
  openssh
  util-linux
  iproute
  iputils
  gcc
  python3
  python3-devel
  make
  libcap-devel
  shadow-utils
  dnf # to be removed
  g++
  git

Hostname=judge

[Runtime]
Firmware=linux