[Distribution]
Distribution=fedora
Release=44
RepositoryKeyFetch=yes

[Output]
Format=directory
OutputDirectory=mkosi.output/

[Content]
Packages=
    systemd
    systemd-networkd
    systemd-resolved
    util-linux
    iproute
    iputils
    gcc
    python3
    python3-devel
    make
    libcap-devel
    shadow-utils

Hostname=judge

[Runtime]
Firmware=linux