# mkosi.conf
[Distribution]
Distribution=fedora
Release=44
RepositoryKeyFetch=yes

[Build]
CacheDirectory=mkosi.cache

[Output]
Format=directory
OutputDirectory=mkosi.output/

[Content]
Packages=
    busybox
    openssh-server
    openssh
    util-linux
    iproute
    iputils
    gcc
    python3
    python3-devel
    make
    libcap-devel
    shadow-utils
    dnf

Hostname=judge

[Runtime]
Firmware=linux