#!/bin/sh

mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t cgroup2 cgroup2 /sys/fs/cgroup
mount -t devtmpfs devtmpfs /dev
mount -t tmpfs tmpfs /tmp

# cgroup setup for isolate
echo "+cpuset +memory" > /sys/fs/cgroup/cgroup.subtree_control
mkdir -p /sys/fs/cgroup/isolate
echo "+cpuset +memory" > /sys/fs/cgroup/isolate/cgroup.subtree_control
mkdir -p /run/isolate/locks

export PATH=/usr/local/bin:$PATH

# fix isolate environment
isolate-check-environment -e &>/dev/null || true
echo ">>> ISOLATE ENVIRONMENT CHECK"
if ! isolate-check-environment; then
  echo ">>> ISOLATE ENVIRONMENT FAILED CHECK"
else
  echo ">>> ISOLATE ENVIRONMENT PASSES CHECK"
fi

# networking
ip link set lo up
ip addr add 127.0.0.1/8 dev lo

/bin/busybox hostname judge-vm