#!/bin/sh

mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t cgroup2 cgroup2 /sys/fs/cgroup
mount -t devtmpfs devtmpfs /dev
mount -t tmpfs tmpfs /tmp

# cgroup setup for isolate
echo "+cpuset +memory" > /sys/fs/cgroup/cgroup.subtree_control
mkdir -p /sys/fs/cgroup/isolate
echo "+cpuset +memory" > /sys/fs/cgroup/isolate/cgroup.subtree_control
mkdir -p /run/isolate/locks

export PATH=/usr/local/bin:$PATH

# fix isolate environment
isolate-check-environment -e &>/dev/null || true
echo ">>> ISOLATE ENVIRONMENT CHECK"
if ! isolate-check-environment; then
  echo ">>> ISOLATE ENVIRONMENT FAILED CHECK"
else
  echo ">>> ISOLATE ENVIRONMENT PASSES CHECK"
fi

echo ">>> Checking for guest binary"
if [ ! -f /app/guest ]; then
  echo ">>> ERROR: Guest binary not found"
else
  echo ">>> Guest binary found!"
fi

if [ ! -f /sbin/reboot ]; then
  echo ">>> ERROR: Reboot binary not found"
else
  echo ">>> Reboot binary found!"
fi

find / | grep -i 'bun'

# networking
# ip link set eth0 up
# ip addr add 172.16.0.2/24 dev eth0
# ip route add default via 172.16.0.1
# echo "nameserver 8.8.8.8" > /etc/resolv.conf

/bin/busybox hostname judge-vm


# ssh-keygen -A
# /usr/sbin/sshd
